[job1]
stats=1
group_reporting=1
ioengine=spdk
thread=1
#readwrite=randread
#bs=128k
#iodepth=16
#time_based=1
#runtime=10s
numjobs=1
cpus_allowed=1
cpus_allowed_policy=split
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=1
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=2
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=3
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=4
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=5
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=6
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=7
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=8
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=9
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=10
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=11
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=12
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=13
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=14
filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=15
#filename=trtype=rdma adrfam=ipv4 traddr=1.1.103.1 trsvcid=4420 ns=16
